apiVersion: v1
kind: Service
metadata:
  name: olm-operator-metrics
spec:
  type: ClusterIP
  ports:
    - name: https-metrics
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: olm-operator
