apiVersion: v1
kind: Service
metadata:
  name: catalog-operator-metrics
  labels:
    app: catalog-operator
    hypershift.openshift.io/control-plane-component: catalog-operator
spec:
  type: ClusterIP
  ports:
    - name: https-metrics
      port: 8443
      protocol: TCP
      targetPort: metrics
  selector:
    app: catalog-operator
